### ISSUE TITLE
cube-gen not working 

### ISSUE THREAD

**Issue by georgeblck** [CAB-LAB/cablab-core#66]
Hello,
I'm trying to use the cube-gen command to create the standard ESDC and other cubes but the command is not working for me right from the beginning.

Here is the error thrown when I try to use `cube-gen --help`:

```
(esdc) user@laptop:~/Documents/cablab-core$ cube-gen --help
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2266, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'cablab' has no attribute 'TestCubeSourceProvider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/esdc/bin/cube-gen", line 11, in <module>
    load_entry_point('cablab-core==0.2.1', 'console_scripts', 'cube-gen')()
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2598, in load_entry_point
    return ep.load()
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/cablab_core-0.2.1-py3.5.egg/cablab/cube_gen.py", line 25, in <module>
    SOURCE_PROVIDERS = _load_source_providers()
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/cablab_core-0.2.1-py3.5.egg/cablab/cube_gen.py", line 16, in _load_source_providers
    source_provider_class = entry_point.load()
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/home/user/anaconda3/envs/esdc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2268, in resolve
    raise ImportError(str(exc))
ImportError: module 'cablab' has no attribute 'TestCubeSourceProvider'
```

I have installed the `cablab-core` as per the instructions in the official [docs](https://cablab.readthedocs.io/en/latest/esdc_access.html). Any help would be appreciated.

**Comment by hans-permana** [comment]
Hi @georgeblck , could you update cablab-core to version 0.2.2? It seems like you are still using the old one that I know has this issue.

**Comment by georgeblck** [comment]
Yes, of course. The update did it, thanks a lot. 
I came upon some other problems which I will post as new issues
